app = "korpotron"
primary_region = "ams"

console_command = "python manage.py shell"

[build]

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8080"

[[vm]]
  memory = "256mb"
  cpus = 1
  cpu_kind = "shared"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  min_machines_running = 1
  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
