# Generated by Django 6.0.5 on 2026-05-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('group', 'name')},
        ),
    ]
