# Generated by Django 6.0.5 on 2026-05-29 16:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_option_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optiongroup',
            unique_together={('user', 'name')},
        ),
    ]
